### ISSUE TITLE
Convert CSV to JSON mapping

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/country_to_locales_mapping#3]
As title.

Take a `hk.json` for example. Something like this.

```json
{
  "name": "HK",
  "description": "Hong Kong",
  "locales": [
    {  "language": "zh", "locale": "HK" },
    {  "language": "en", "locale": "HK" },
    {  "language": "zh", "locale": "Hant-HK" },
    {  "language": "zh", "locale": "Hant" },
  ]
}
```

**Comment by skalee** [comment]
Done on `json` branch (not merged yet due to some Travis glitch), but I've maintained previous locale format which is compatible with RFC4646. It looks like as follows:

```json
{
  "countries": {
    "HK": {
      "name": "Hong Kong",
      "locales": [
        "zh-HK",
        "en-HK",
        "zh-Hant-HK",
        "zh-Hant"
      ]
    }
  }
}
```

**Comment by ronaldtse** [comment]
Nice work, @skalee might want to break the file down to individual countries `.json` files for easy management and merging of PRs in the future.

**Comment by skalee** [comment]
@ronaldtse Final JSON is a multi-line diffable text file, so I believe that makes it manageable enough. Please create respective issue if you disagree.

If the intention of JSON file was to access it from some JavaScript, then perhaps we should release an NPM package as well? Please create respective issue if yes.

**Comment by ronaldtse** [comment]
Thanks @skalee , created #8 for NPM package!
